// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvZ5wyJ7hw5WJ5y-Mqe0tfO80xOhouug4',
    appId: '1:267790599950:web:a686379d93f3bf52bcf95f',
    messagingSenderId: '267790599950',
    projectId: 'ic14-13eca',
    authDomain: 'ic14-13eca.firebaseapp.com',
    storageBucket: 'ic14-13eca.firebasestorage.app',
    measurementId: 'G-PLY9RHFHW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzuun6tvdsE3OB0EWkzvTGy3cLsnqfBHQ',
    appId: '1:267790599950:android:db972d325241b96cbcf95f',
    messagingSenderId: '267790599950',
    projectId: 'ic14-13eca',
    storageBucket: 'ic14-13eca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiZC-m8smeV_XQ7BdV54KN7_dOzuZLxRU',
    appId: '1:267790599950:ios:d4dcaadf81f20bb1bcf95f',
    messagingSenderId: '267790599950',
    projectId: 'ic14-13eca',
    storageBucket: 'ic14-13eca.firebasestorage.app',
    iosBundleId: 'com.example.icw14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiZC-m8smeV_XQ7BdV54KN7_dOzuZLxRU',
    appId: '1:267790599950:ios:d4dcaadf81f20bb1bcf95f',
    messagingSenderId: '267790599950',
    projectId: 'ic14-13eca',
    storageBucket: 'ic14-13eca.firebasestorage.app',
    iosBundleId: 'com.example.icw14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvZ5wyJ7hw5WJ5y-Mqe0tfO80xOhouug4',
    appId: '1:267790599950:web:4b5ca0787b28c4ccbcf95f',
    messagingSenderId: '267790599950',
    projectId: 'ic14-13eca',
    authDomain: 'ic14-13eca.firebaseapp.com',
    storageBucket: 'ic14-13eca.firebasestorage.app',
    measurementId: 'G-SL8DKWC6YR',
  );
}
